services:
  - type: web
    name: meu-pedido-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: DB_USER
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: 5432
      - key: JWT_SECRET
        generateValue: true